name: PHP version action
description:
  An action to use the minimum and the latest version of PHP (as defined in composer.json) and build version matrix in
  between
author: Antoine Froger

branding:
  icon: bar-chart-2
  color: green

inputs:
  working-directory:
    description: Directory containing your composer.json file
    required: true
    default: .
  unstable:
    description: Include unstable versions of PHP (beta, release candidates)
    required: true
    default: false
  unsupported:
    description: Include unsupported versions of PHP (EOL and no security support)
    required: true
    default: true

outputs:
  composer-php-version:
    description: The PHP version requirement from composer.json, f.e. >=8.1 <=8.4
  minimal:
    description: The minimum supported PHP version meeting the requirements, f.e. 8.1
  latest:
    description: The latest available PHP version meeting the requirements, f.e. 8.4
  matrix:
    description: A (stringified) array of PHP versions from min to latest, f.e. [8.1, 8.2, 8.3, 8.4]

runs:
  using: node22
  main: dist/index.js
