name: PHP version action
description:
  A GitHub action to use the latest released version of PHP, the minimum supported version (as defined in composer.json
  of your project), and a build matrix for all versions in between.
author: Antoine Froger

branding:
  icon: bar-chart-2
  color: green

inputs:
  working-directory:
    description: Directory containing your composer.json file
    required: true
    default: .

outputs:
  composer-php-version:
    description: The PHP version requirement from composer.json, f.e. >=8.1 <=8.4
  minimal:
    description: The minimum supported PHP version meeting the requirements, f.e. 8.1
  latest:
    description: The latest available PHP version meeting the requirements, f.e. 8.4
  matrix:
    description: A (stringified) array of PHP versions from min to latest, f.e. [8.1, 8.2, 8.3, 8.4]

runs:
  using: node20
  main: dist/index.js
