name: PHP version action
description:
  A GitHub action to use the latest released version of PHP, the minimum supported version (as defined in composer.json
  of your project), and a build matrix for all versions in between.
author: Antoine Froger

branding:
  icon: bar-chart-2
  color: green

inputs:
  working-directory:
    description: Working directory where your composer.json file is located
    required: true
    default: .

outputs:
  composer-php-version:
    description: The PHP version specified in composer.json
  minimal:
    description: The minimal PHP version
  latest:
    description: The latest PHP version
  matrix:
    description: A (stringified) array of PHP versions from the minimal supported version to the latest released version

runs:
  using: node20
  main: dist/index.js
