name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Test Local Action with all versions
        id: all-versions
        uses: ./
        with:
          working-directory: ./__tests__/testdata

      - run: |
          expected=">=8.2"
          actual="${{ steps.all-versions.outputs.composer-php-version }}"

          if [ "$actual" != "$expected" ]; then
            echo "❌ composer-php-version mismatch:"
            echo "  Expected: $expected"
            echo "  Actual:   $actual"
            exit 1
          fi
          echo "✅ composer-php-version matches expected: $actual"

      - run: |
          expected="8.2"
          actual="${{ steps.all-versions.outputs.minimal }}"

          if [ "$actual" != "$expected" ]; then
            echo "❌ minimal version mismatch:"
            echo "  Expected: $expected"
            echo "  Actual:   $actual"
            exit 1
          fi
          echo "✅ minimal version matches expected: $actual"

      - run: |
          expected="8.4"
          actual="${{ steps.all-versions.outputs.latest }}"

          if [ "$actual" != "$expected" ]; then
            echo "❌ latest version mismatch:"
            echo "  Expected: $expected"
            echo "  Actual:   $actual"
            exit 1
          fi
          echo "✅ latest version matches expected: $actual"

      - run: |
          expected='["8.2","8.3","8.4"]'
          actual="${{ steps.all-versions.outputs.matrix }}"

          if [ "$actual" != "$expected" ]; then
            exit 1
          fi
